<!DOCTYPE HTML>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Your Website</title>
	<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.5/material.indigo-pink.min.css">
	<script src="https://storage.googleapis.com/code.getmdl.io/1.0.5/material.min.js"></script>
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>

<body>

	<!-- Uses a transparent header that draws on top of the layout's background -->
	<style>
	.demo-layout-transparent {
	  background: url('../assets/images/transparent.jpg') center / cover;
	}
	.demo-layout-transparent .mdl-layout__header,
	.demo-layout-transparent .mdl-layout__drawer-button {
	  /* This background is dark, so we set text to white. Use 87% black instead if
		 your background is light. */
	  color: white;
	}
	</style>

	<div class="demo-layout-transparent mdl-layout mdl-js-layout">
	  <header class="mdl-layout__header mdl-layout__header--transparent">
		<div class="mdl-layout__header-row">
		  <!-- Title -->
		  <span class="mdl-layout-title">Title</span>
		  <!-- Add spacer, to align navigation to the right -->
		  <div class="mdl-layout-spacer"></div>
		  <!-- Navigation -->
		  <nav class="mdl-navigation">
			<a class="mdl-navigation__link" href="">Link</a>
			<a class="mdl-navigation__link" href="">Link</a>
			<a class="mdl-navigation__link" href="">Link</a>
			<a class="mdl-navigation__link" href="">Link</a>
		  </nav>
		</div>
	  </header>
	  <div class="mdl-layout__drawer">
		<span class="mdl-layout-title">Title</span>
		<nav class="mdl-navigation">
		  <a class="mdl-navigation__link" href="">Link</a>
		  <a class="mdl-navigation__link" href="">Link</a>
		  <a class="mdl-navigation__link" href="">Link</a>
		  <a class="mdl-navigation__link" href="">Link</a>
		</nav>
	  </div>
	  <main class="mdl-layout__content">
	  </main>
	</div>
	
	<!--header>
		<nav>
			<ul>
				<li>Your menu</li>
			</ul>
		</nav>
	</header>
	
	<section>
	
		<article>
			<header>
				<h2>Article title</h2>
				<p>Posted on <time datetime="2009-09-04T16:31:24+02:00">September 4th 2009</time> by <a href="#">Writer</a> - <a href="#comments">6 comments</a></p>
			</header>
			<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
		</article>
		
		<article>
			<header>
				<h2>Article title</h2>
				<p>Posted on <time datetime="2009-09-04T16:31:24+02:00">September 4th 2009</time> by <a href="#">Writer</a> - <a href="#comments">6 comments</a></p>
			</header>
			<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
		</article>
		
	</section>

	<aside>
		<h2>About section</h2>
		<p>Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
	</aside>

	<footer>
		<p>Copyright 2009 Your name</p>
	</footer-->

</body>

</html>